# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "ee1f8232a939f3a7a961ea76d3315c4f044587c3"

[[deps.MassExport]]
git-tree-sha1 = "5984e7744efc52f69088103eb196aa8fa4c4da9e"
uuid = "bdad8087-1bf2-41e1-917c-1d9e34c2a82c"
version = "1.0.3"

[[deps.Simuleos]]
deps = ["MassExport"]
path = "."
uuid = "583fa42a-a17c-4ad2-8932-70aab3cc9651"
version = "0.1.0"
