name = "Simuleos"
uuid = "583fa42a-a17c-4ad2-8932-70aab3cc9651"
version = "0.1.0"
authors = ["josePereiro <jose.pereiro.lab@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MassExport = "bdad8087-1bf2-41e1-917c-1d9e34c2a82c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
MassExport = "1.0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
