name = "Simuleos"
uuid = "583fa42a-a17c-4ad2-8932-70aab3cc9651"
version = "0.1.0"
authors = ["josePereiro <jose.pereiro.lab@gmail.com>"]

[deps]
MassExport = "bdad8087-1bf2-41e1-917c-1d9e34c2a82c"

[compat]
MassExport = "1.0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
